language: android
jdk: oraclejdk8
env:
  global:
    - ANDROID_TARGET=android-17
    - ANDROID_ABI=armeabi-v7a
android:
  components:
    # The BuildTools used by us
    - build-tools-26.0.2

    # The SDK we build against
    - android-27

  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

before_install:
    - mkdir "$ANDROID_HOME/licenses" || true
    - echo -e "\nd56f5187479451eabf01fb78af6dfcb131a6481e\n8933bad161af4178b1185d1a37fbf41ea5269c55" >> "$ANDROID_HOME/licenses/android-sdk-license"

script:

  - ./gradlew test

cache:
  directories:
    - $HOME/.gradle/wrapper
    - $HOME/.gradle/caches
    - $HOME/.android/build-cache
