language: android
jdk: oraclejdk8
env:
  global:
    - ANDROID_TARGET=android-17
    - ANDROID_ABI=armeabi-v7a
android:
  components:
    - tools
    - platform-tools
    # Duplicated on purpose!
    - tools 

    # The BuildTools used by us
    - build-tools-26.0.2

    # The SDK we build against
    - android-27
    - sys-img-${ANDROID_ABI}-${ANDROID_TARGET}
script:
  - ./gradlew test
