language: android
jdk: oraclejdk8
env:
  global:
    - ANDROID_TARGET=android-17
    - ANDROID_ABI=armeabi-v7a
android:
  components:
    # The BuildTools used by us
    - build-tools-26.0.2

    # The SDK we build against
    - android-27

  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

install:
  - echo y | android update sdk -u -a -t android-27

script:

  - ./gradlew test

cache:
  directories:
    - $HOME/.gradle/wrapper
    - $HOME/.gradle/caches
    - $HOME/.android/build-cache