language: android
jdk: oraclejdk8
env:
  global:
    - ANDROID_ABI=armeabi-v7a
  matrix:
    - ANDROID_TARGET=android-17
    - ANDROID_TARGET=android-20
    - ANRDOID_TARGET=android-21
    - ANDROID_TARGET=android-27
android:
  components:
    # The BuildTools used by us
    - build-tools-26.0.2

    # The SDK we build against
    - ${ANDROID_TARGET}

  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

script:
  - ./gradlew lint
  - ./gradlew test

cache:
  directories:
    - $HOME/.gradle/wrapper
    - $HOME/.gradle/caches
    - $HOME/.android/build-cache
